import { HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { UserCreateDto } from './dto/user-create.dto';
import { User } from './user.entity';

@Injectable()
export class UserService {
  constructor(
    @InjectRepository(User) private readonly userRepository: Repository<User>,
  ) {}

  /**
   * this method searches for a user by email
   * @param email email of the user to be found
   * @returns return the found user
   */
  public async getByEmail(email: string): Promise<User> {
    const user = await this.userRepository.findOne({ where: { email } });
    if (user) return user;
    throw new HttpException(
      'User with this email does not exist',
      HttpStatus.NOT_FOUND,
    );
  }

  /**
   * this method crestes a new user
   * @param user generated by the user
   * @returns return the created user
   */
  public async create(user: UserCreateDto): Promise<User> {
    return await this.userRepository.save(user);
  }

  /**
   * this method searches for a user by id
   * @param id id of the user to be found
   * @returns return the found user
   */
  public async getById(id: number): Promise<User> {
    const user = await this.userRepository.findOne({ where: { id } });
    if (user) return user;
    throw new HttpException(
      'User with this id does not exist',
      HttpStatus.NOT_FOUND,
    );
  }
}
